### ISSUE TITLE
The response of tafsirs are same

### ISSUE THREAD

**Issue by Wreaking** [spa5k/tafsir_api#5]
Assalamualaikum wa rahmatullahi wa barakatuh, first of all, may Allah SWT accept your repentance and grant you Jannah on the Day of Judgment. Jazakallah khair for providing the API. The issue is that the tafsir of "en-tafsir-al-tustari" and "en-kashf-al-asrar-tafsir" are the same. Could you please check if there has been a mistake made, as the responses on https://www.altafsir.com are different between the two books by the same authors?

Jazakallah khair.

**Comment by spa5k** [comment]
Wa iyaakum, let me check.

**Comment by spa5k** [comment]
There were probably some mistakes in downloading it, so deleted these 2 Tafsirs and ran the program again. Seems to be fixed.

**Comment by Wreaking** [comment]
jazakallah khair for fixing it

**Comment by Wreaking** [comment]
alright, theres also the symbol "?�" coming up in those 2 tafsirs

**Comment by spa5k** [comment]
Thats the problem with your font, not tafsir, it requires special arabic font. https://github.com/fawazahmed0/quran-api check here for the fonts

**Comment by Wreaking** [comment]
jazakallah khair ,i fixed it long ago and sorry for the late reply
